[phases.setup]
nixPkgs = [
  "python313",
  "glib",
  "gtk3",
  "nss",
  "nspr",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXrender",
  "xorg.libXtst",
  "xorg.libxcb",
  "libdrm",
  "mesa",
  "pango",
  "cairo",
  "atk",
  "at-spi2-atk",
  "alsa-lib",
  "cups",
  "dbus",
  "expat",
  "fontconfig",
  "freetype",
  "glibc",
  "libuuid"
]
